backstage:
  image:
    registry: quay.io
    repository: carlosthe19916/backstage
    tag: latest
    pullPolicy: Always
  command:
    - node
    - packages/backend
    - --config
    - app-config.yaml
    - --config
    - app-config.production.yaml
  extraAppConfig:    
    - filename: config-map.prod.yaml
      configMapRef: backstage-configmap
  extraEnvVarsSecrets:
    - backstage-secrets
postgresql:
  enabled: true
