backstage:
  image:
    repository: carlosthe19916/backstage
    tag: latest
    pullPolicy: Always
  command:
    - node
    - packages/backend
    - --config
    - app-config.yaml
    - --config
    - app-config.production.yaml
  extraEnvVars:
    - name: BACKEND_SECRET
      value: "xiaXDwU++YmGzvIdQ/g3pJti7hM2j2CS"
postgresql:
  enabled: true
